name: Netology Goblin

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build:
    needs: [eslint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4